version: 2
jobs:
  build:
    working_directory: ~/sparkt-ast-hs
    machine: true
    steps:
      - checkout

      - restore_cache:
          key: cache

      - run: wget https://github.com/commercialhaskell/stack/releases/download/v1.5.1/stack-1.5.1-freebsd-x86_64.tar.gz -O /tmp/stack.gz
      - run: gunzip /tmp/stack.gz && chmod +x /tmp/stack
      - run: sudo mv /tmp/stack /usr/bin/stack      
      - run: stack setup
      - run: stack build --fast

      - save_cache:
          paths:
            - ~/.stack
          key: cache

      - run: stack test --no-terminal --coverage
      - run: stack exec -- shc --repo-token=$COVERALLS_REPO_TOKEN Uthenga uthenga-test
